export default function RecoveryRoadmap({ roadmap }) {
    if (!roadmap || roadmap.length === 0) return null

    return (
        <div className="card animate-fade-in-up" style={{ padding: '28px', marginTop: '20px', animationDelay: '0.2s' }}>
            {/* Header */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '28px' }}>
                <div style={{
                    width: '44px', height: '44px', borderRadius: '12px',
                    background: 'linear-gradient(135deg, rgba(255,153,51,0.2), rgba(255,153,51,0.05))',
                    border: '1px solid rgba(255,153,51,0.3)',
                    display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.25rem',
                }}>
                    🗺️
                </div>
                <div>
                    <h3 style={{ fontFamily: 'var(--font-display)', fontSize: '1.1rem', fontWeight: 700 }}>
                        6-Month Recovery Roadmap
                    </h3>
                    <p style={{ fontSize: '0.75rem', color: 'var(--color-slate-light)', marginTop: '2px' }}>
                        Personalised intervention plan · Auto-generated by Shiksha Shield AI
                    </p>
                </div>
                <div style={{ marginLeft: 'auto' }}>
                    <span className="badge badge-critical" style={{ fontSize: '0.65rem' }}>
                        🔴 HIGH PRIORITY
                    </span>
                </div>
            </div>

            {/* Timeline */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
                {roadmap.map((item, i) => (
                    <div key={i} className="timeline-item">
                        <div className="timeline-dot" style={{ animationDelay: `${i * 0.1}s` }}>
                            {item.icon}
                        </div>
                        <div style={{
                            flex: 1,
                            background: 'rgba(255,255,255,0.02)',
                            border: '1px solid rgba(255,255,255,0.07)',
                            borderRadius: '12px',
                            padding: '16px',
                            marginBottom: '4px',
                        }}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px', flexWrap: 'wrap', gap: '8px' }}>
                                <span style={{
                                    background: 'rgba(255,153,51,0.1)',
                                    color: 'var(--color-saffron)',
                                    border: '1px solid rgba(255,153,51,0.2)',
                                    borderRadius: '100px',
                                    padding: '3px 10px',
                                    fontSize: '0.7rem',
                                    fontWeight: 700,
                                    letterSpacing: '0.05em',
                                }}>
                                    📅 {item.month_range}
                                </span>
                                <span style={{
                                    fontSize: '0.7rem',
                                    color: 'var(--color-slate-light)',
                                    display: 'flex', alignItems: 'center', gap: '5px',
                                }}>
                                    👤 {item.responsible}
                                </span>
                            </div>
                            <p style={{ fontSize: '0.85rem', lineHeight: 1.6, color: 'rgba(248,250,252,0.85)' }}>
                                {item.action}
                            </p>
                        </div>
                    </div>
                ))}
            </div>

            {/* Footer */}
            <div style={{
                marginTop: '20px',
                background: 'rgba(16,185,129,0.06)',
                border: '1px solid rgba(16,185,129,0.15)',
                borderRadius: '10px',
                padding: '12px 16px',
                fontSize: '0.78rem',
                color: 'var(--color-emerald-light)',
                display: 'flex', alignItems: 'center', gap: '8px',
            }}>
                ✅ <strong>Next Review:</strong> Schedule follow-up assessment in 30 days. Document all interventions in the Shiksha Shield tracker.
            </div>
        </div>
    )
}
